<?php

declare(strict_types=1);

use App\Modules\Identity\Application\ClientContext;
use App\Modules\Identity\Application\DisableAccount;
use App\Modules\Identity\Application\ResetPassword;
use App\Modules\Identity\Domain\Account;
use App\Modules\Identity\Domain\AccountRepository;
use App\Modules\Identity\Domain\EmailAddress;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Tests\Support\Console;
use Tests\Support\Identity;
use Tests\Support\Mfa;
use Tests\Support\Passwords;
use Tests\Support\Recovery;
use Tests\Support\Totp;

/*
 * Signing in with an authenticator (ADR 0023): the password proves the first factor and starts a pending
 * sign-in; only a valid code (or recovery code) turns it into a session.
 */

beforeEach(function () {
    Carbon::setTestNow('2026-09-19 12:00:00');
    Mfa::registerProbeRoutes();
});

/**
 * An enrolled Console Account, with the password proved: a Console holding a pending challenge.
 *
 * @return array{Console, Account, array{secret: string, codes: list<string>}}
 */
function pendingChallenge(): array
{
    $account = Mfa::guardian();
    $factor = Mfa::enroll($account);
    $console = new Console;
    $console->login('ada@example.org', Identity::PASSWORD)->assertStatus(202)->assertExactJson(['next' => 'challenge', 'expires_at' => '2026-09-19T12:05:00Z']);

    return [$console, $account, $factor];
}

it('does not sign in on a correct password alone: /me and every gate stay unauthenticated', function () {
    [$console, $account] = pendingChallenge();

    $console->me()->assertUnauthorized();
    $console->get('/api/v1/zz/console')->assertUnauthorized();
    $console->post('/api/v1/password/change', ['current_password' => Identity::PASSWORD, 'password' => Passwords::STRONG, 'password_confirmation' => Passwords::STRONG])->assertUnauthorized();
    expect(DB::table('sessions')->whereNotNull('user_id')->count())->toBe(0)
        ->and(app(AccountRepository::class)->find($account->id)?->lastLoginAt)->toBeNull()
        ->and(Identity::events('authentication.succeeded'))->toBe([]);
});

it('holds only the minimum in the pending sign-in: no password, hash, secret, code or capability', function () {
    [$console, , $factor] = pendingChallenge();
    $stored = Mfa::text(DB::table('sessions')->latest('last_activity')->value('payload'));
    $decoded = (string) base64_decode($stored, true);
    expect($decoded)->toContain('pending_sign_in');   // what is held is there to be inspected

    foreach ([Identity::PASSWORD, $factor['secret'], 'console.access', 'guardian', ...array_map(fn ($c) => str_replace('-', '', $c), $factor['codes'])] as $forbidden) {
        expect($stored.$decoded)->not->toContain($forbidden);
    }
    $accountHash = Mfa::text(DB::table('accounts')->value('password_hash'));
    expect($stored.$decoded)->not->toContain($accountHash);
});

it('completes the sign-in with a valid code: a fresh session, provenance, and the same limits', function () {
    [$console, $account, $factor] = pendingChallenge();
    $before = $console->cookie(Console::SESSION_COOKIE)?->getValue();
    $beforeToken = $console->cookie(Console::XSRF_COOKIE)?->getValue();

    $response = $console->challenge($factor['secret'])->assertOk()
        ->assertJsonPath('account.email', 'ada@example.org')
        ->assertJsonPath('capabilities', ['console.access'])
        ->assertJsonPath('session.absolute_expires_at', '2026-09-20T00:00:00Z')
        ->assertJsonPath('mfa.enrolled', true)
        ->assertJsonPath('mfa.recovery_codes_remaining', 10);

    expect($response->json('session.authenticated_at'))->toBe('2026-09-19T12:00:00Z');
    // The session id and CSRF token were both regenerated by completing the sign-in.
    expect($console->cookie(Console::SESSION_COOKIE)?->getValue())->not->toBe($before)
        ->and($console->cookie(Console::XSRF_COOKIE)?->getValue())->not->toBe($beforeToken);
    $console->me()->assertOk();
    $console->get('/api/v1/zz/actor')->assertOk()->assertJson(['via' => 'session_second_factor']);
    expect(app(AccountRepository::class)->find($account->id)?->lastLoginAt)->not->toBeNull()
        ->and(Identity::context(Identity::events('authentication.succeeded')[0]))->toBe(['method' => 'password', 'second_factor' => 'totp']);
});

it('still bounds the session by the same 30 minutes of inactivity and 12 hours', function () {
    [$console, , $factor] = pendingChallenge();
    $console->challenge($factor['secret'])->assertOk();

    Console::advance(31 * 60);
    $console->me()->assertUnauthorized();
});

it('refuses a wrong code, and stays signed out', function () {
    [$console, $account] = pendingChallenge();

    $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable()->assertJsonPath('errors.code.0', 'The code is not valid.');

    $console->me()->assertUnauthorized();
    expect(app(AccountRepository::class)->find($account->id)?->lastLoginAt)->toBeNull();
    $failed = Identity::events('mfa.challenge_failed');
    expect($failed)->toHaveCount(1)
        ->and($failed[0]->subject_account_id)->toBe($account->id->value)
        ->and($failed[0]->outcome)->toBe('failure')
        ->and(Identity::context($failed[0]))->toBe(['reason' => 'invalid_code', 'during' => 'sign_in'])
        ->and(Mfa::auditText())->not->toContain('000000');
});

it('needs exactly one of a code and a recovery code', function (array $body) {
    /** @var array<string, mixed> $body */
    [$console] = pendingChallenge();

    $console->post('/api/v1/mfa/challenge', $body)->assertUnprocessable();
})->with([
    'neither' => [[]],
    'both' => [['code' => '123456', 'recovery_code' => 'ABCD-EFGH-JKMN-PQRS']],
    'a code that is not text' => [['code' => ['123456']]],
]);

it('gives a wrong or malformed code the same answer, whatever it is', function (string $code) {
    [$console] = pendingChallenge();

    $response = $console->post('/api/v1/mfa/challenge', ['code' => $code])->assertUnprocessable();

    expect($response->json('errors'))->toBe(['code' => ['The code is not valid.']]);
})->with(['wrong' => '654321', 'short' => '12', 'letters' => 'abcdef', 'long' => '12345678901234567890']);

it('lets the challenge expire five minutes after the password, and then a correct code does nothing', function () {
    [$console, , $factor] = pendingChallenge();

    Console::advance(301);

    $console->challenge($factor['secret'])->assertUnauthorized()->assertJson(['message' => 'This sign-in has expired. Sign in again.']);
    $console->me()->assertUnauthorized();
});

it('does not extend the challenge by activity: five minutes from the password, however busy', function () {
    [$console, , $factor] = pendingChallenge();

    Console::advance(200);
    $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable();
    Console::advance(101);

    $console->challenge($factor['secret'])->assertUnauthorized();
});

it('answers an expired, ended or absent challenge with the same words, revealing nothing about the Account', function () {
    [$console, , $factor] = pendingChallenge();
    Console::advance(301);
    $expired = $console->challenge($factor['secret'])->assertUnauthorized();

    $stranger = new Console;
    $stranger->bootstrap();
    $absent = $stranger->post('/api/v1/mfa/challenge', ['code' => '123456'])->assertUnauthorized();

    expect($expired->getContent())->toBe($absent->getContent());
});

it('consumes the challenge on success: it cannot be used a second time', function () {
    [$console, , $factor] = pendingChallenge();
    $console->challenge($factor['secret'])->assertOk();

    $console->post('/api/v1/mfa/challenge', ['code' => Totp::next($factor['secret'])])->assertUnauthorized();
});

it('ends the pending sign-in after five wrong codes: the password must be proved again', function () {
    [$console, , $factor] = pendingChallenge();

    for ($i = 0; $i < 4; $i++) {
        $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable();
    }
    // The fifth wrong code ends it: even a correct code cannot finish it now.
    $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable();
    $console->challenge($factor['secret'])->assertUnauthorized();

    // Four wrong codes do NOT: ordinary typing mistakes are not a lockout.
});

it('tolerates ordinary typing mistakes: four wrong codes and then the right one', function () {
    [$console, , $factor] = pendingChallenge();

    for ($i = 0; $i < 4; $i++) {
        $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable();
    }

    $console->challenge($factor['secret'])->assertOk();
});

it('rate limits codes per Account, whatever the pending sign-in, and audits the limit once', function () {
    config(['identity.credential_throttle.mfa_challenge.per_identifier' => 3]);
    [$console, , $factor] = pendingChallenge();

    for ($i = 0; $i < 3; $i++) {
        $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable();
    }

    $blocked = $console->post('/api/v1/mfa/challenge', ['code' => Totp::next($factor['secret'])])->assertStatus(429);
    $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertStatus(429);
    expect((int) $blocked->headers->get('Retry-After'))->toBeGreaterThan(0);
    $limited = Identity::events('authentication.rate_limited');
    expect($limited)->toHaveCount(1)
        ->and(Identity::context($limited[0]))->toMatchArray(['action' => 'mfa_challenge', 'scope' => 'identifier']);
    $console->me()->assertUnauthorized();
});

it('rate limits codes per source address as well', function () {
    config(['identity.credential_throttle.mfa_challenge.per_ip' => 2]);
    [$console] = pendingChallenge();

    $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable();
    $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable();

    $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertStatus(429);
});

it('does not let an Account disabled after its password was accepted finish signing in', function () {
    [$console, $account, $factor] = pendingChallenge();

    app(DisableAccount::class)($account->id);

    $console->challenge($factor['secret'])->assertUnauthorized();
    $console->me()->assertUnauthorized();
    expect(DB::table('sessions')->whereNotNull('user_id')->count())->toBe(0)
        ->and(app(AccountRepository::class)->find($account->id)?->lastLoginAt)->toBeNull();
    expect(Identity::context(Identity::events('mfa.challenge_failed')[0]))->toBe(['reason' => 'account_not_active', 'during' => 'sign_in']);
});

it('does not let a password replaced after it was proved finish the sign-in (a reset)', function () {
    [$console, $account, $factor] = pendingChallenge();

    app(ResetPassword::class)(EmailAddress::fromString('ada@example.org'), Recovery::tokenFor($account), Passwords::STRONG, new ClientContext('127.0.0.1', 'test'));

    $console->challenge($factor['secret'])->assertUnauthorized();
    expect(DB::table('sessions')->whereNotNull('user_id')->count())->toBe(0)
        ->and(Identity::context(Identity::events('mfa.challenge_failed')[0]))->toBe(['reason' => 'credential_changed', 'during' => 'sign_in']);
});

it('does not let a password replaced by another sign-in of the same Account finish it (a change)', function () {
    [$console, $account, $factor] = pendingChallenge();
    // The person is signed in on another device and changes the password there.
    $other = new Console;
    $other->loginWithMfa('ada@example.org', Identity::PASSWORD, $factor['secret'])->assertOk();
    $other->post('/api/v1/password/change', ['current_password' => Identity::PASSWORD, 'password' => Passwords::STRONG, 'password_confirmation' => Passwords::STRONG])->assertNoContent();

    $console->challenge($factor['secret'])->assertUnauthorized();
    $console->me()->assertUnauthorized();
});

it('binds the pending sign-in to the credential itself, not to a timestamp: a replacement in the SAME second is caught', function () {
    [$console, $account, $factor] = pendingChallenge();
    // Same instant (the clock is frozen), same everything but the stored hash.
    $current = app(AccountRepository::class)->find($account->id);
    assert($current !== null);
    app(AccountRepository::class)->save(Account::reconstitute(
        $current->id, $current->personId, $current->email, $current->status, Hash::make('a brand new passphrase'),
        $current->passwordUpdatedAt, $current->emailVerifiedAt, $current->disabledAt, $current->lastLoginAt, $current->createdAt, $current->updatedAt,
    ));

    $console->challenge($factor['secret'])->assertUnauthorized();
});

it('catches even the SAME password text set again, since every stored hash is salted afresh', function () {
    [$console, $account, $factor] = pendingChallenge();
    $current = app(AccountRepository::class)->find($account->id);
    assert($current !== null);
    app(AccountRepository::class)->save(Account::reconstitute(
        $current->id, $current->personId, $current->email, $current->status, Hash::make(Identity::PASSWORD),
        $current->passwordUpdatedAt, $current->emailVerifiedAt, $current->disabledAt, $current->lastLoginAt, $current->createdAt, $current->updatedAt,
    ));

    $console->challenge($factor['secret'])->assertUnauthorized();
});

it('lets an unrelated change to the Account through: the binding is to the credential and nothing else', function () {
    [$console, $account, $factor] = pendingChallenge();
    $current = app(AccountRepository::class)->find($account->id);
    assert($current !== null);
    app(AccountRepository::class)->save($current->recordLogin(Identity::now()->modify('+5 seconds')));

    $console->challenge($factor['secret'])->assertOk();
});

it('accepts a code from a step either side of now, and no wider', function () {
    [$console, $account, $factor] = pendingChallenge();
    $now = Carbon::now()->getTimestamp();
    $step = Totp::step($now);

    // Two steps old: refused. One step old: accepted.
    $console->post('/api/v1/mfa/challenge', ['code' => Totp::forStep($factor['secret'], $step - 2)])->assertUnprocessable();
    $console->post('/api/v1/mfa/challenge', ['code' => Totp::forStep($factor['secret'], $step + 2)])->assertUnprocessable();
    $console->post('/api/v1/mfa/challenge', ['code' => Totp::forStep($factor['secret'], $step - 1)])->assertOk();
});

it('accepts a code with spaces in it, the way people type them', function () {
    [$console, , $factor] = pendingChallenge();
    $code = Totp::next($factor['secret']);

    $console->post('/api/v1/mfa/challenge', ['code' => substr($code, 0, 3).' '.substr($code, 3)])->assertOk();
});

it('accepts each code once: replaying a used code is refused, and the next step works', function () {
    [$console, $account, $factor] = pendingChallenge();
    $used = Totp::next($factor['secret']);
    $console->post('/api/v1/mfa/challenge', ['code' => $used])->assertOk();

    // A second sign-in in the same time step, with the very same code.
    $again = new Console;
    $again->login('ada@example.org', Identity::PASSWORD)->assertStatus(202);
    $again->post('/api/v1/mfa/challenge', ['code' => $used])->assertUnprocessable();
    $again->me()->assertUnauthorized();

    $again->post('/api/v1/mfa/challenge', ['code' => Totp::next($factor['secret'])])->assertOk();
});

it('never leaves the Account without a way in when a code is refused: the factor is unchanged', function () {
    [$console, $account, $factor] = pendingChallenge();
    $before = Mfa::factorRow($account);

    $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable();

    expect(Mfa::factorRow($account))->toEqual($before);
});

it('asks an Account that has an authenticator for it even when its access no longer needs one', function () {
    $account = Identity::savedActiveAccount();   // holds no role: nothing requires a second factor
    Mfa::enroll($account);

    (new Console)->login('ada@example.org', Identity::PASSWORD)->assertStatus(202)->assertJson(['next' => 'challenge']);
});

it('records a sign-in by authenticator with the method, and no code', function () {
    [$console, , $factor] = pendingChallenge();
    $code = Totp::next($factor['secret']);
    $console->post('/api/v1/mfa/challenge', ['code' => $code])->assertOk();

    Mfa::assertAbsent(Mfa::auditText(), $code, $factor['secret'], Identity::PASSWORD);
});

it('does not multiply session rows: one browser is one row from the first visit to the signed-in session', function () {
    // The Console's start-up /me already creates an anonymous session row per visit (a known follow-up). The
    // pending sign-in must add none of its own: it REPLACES that row, and completing the sign-in replaces it again.
    $account = Mfa::guardian();
    $factor = Mfa::enroll($account);
    $console = new Console;

    $console->bootstrap();
    expect(DB::table('sessions')->count())->toBe(1);

    $console->login('ada@example.org', Identity::PASSWORD)->assertStatus(202);
    expect(DB::table('sessions')->count())->toBe(1)
        ->and(DB::table('sessions')->whereNotNull('user_id')->count())->toBe(0);

    $console->post('/api/v1/mfa/challenge', ['code' => '000000'])->assertUnprocessable();
    expect(DB::table('sessions')->count())->toBe(1);

    $console->challenge($factor['secret'])->assertOk();
    expect(DB::table('sessions')->count())->toBe(1)
        ->and(DB::table('sessions')->whereNotNull('user_id')->count())->toBe(1);
});

it('leaves no pending sign-in behind when a second password sign-in replaces it', function () {
    Mfa::enroll(Mfa::guardian());
    $console = new Console;
    $console->login('ada@example.org', Identity::PASSWORD)->assertStatus(202);

    $console->login('ada@example.org', Identity::PASSWORD)->assertStatus(202);

    expect(DB::table('sessions')->count())->toBe(1);
});
