import { expect, test, type Page } from '@playwright/test'

import { nextCode } from './support.ts'

// Real Chromium against the real gateway: Guardian Console session authentication
// (ADR 0016). The account is the development fixture seeded by `./flow test e2e`
// (apps/platform/database/seeders/E2eAccountSeeder.php); its credentials are public.
//
// The session mechanics (cookie, CSRF, regeneration) are measured with an account whose access does not need a
// second factor. A Console user's sign-in is two steps (ADR 0023), which is measured here too: a password alone
// establishes NO session, and the code does.
const EMAIL = 'e2e.session@example.org'
const PASSWORD = 'e2e-session-password-not-a-secret'
const GUARDIAN = 'e2e.guardian@example.org'
const GUARDIAN_PASSWORD = 'e2e-fixture-password-not-a-secret'
const GUARDIAN_SECRET = 'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ'
const SESSION_COOKIE = '__Host-flowlife-session'
const HOST = 'commons.flowlife.localhost'

interface Api {
  status: number
  body: unknown
}

/** The CSRF token the way the Console's HTTP client reads it: from the XSRF-TOKEN cookie. */
async function xsrfToken(page: Page): Promise<string | undefined> {
  const found = (await page.context().cookies()).find((c) => c.name === 'XSRF-TOKEN')
  return found === undefined ? undefined : decodeURIComponent(found.value)
}

/** A same-origin fetch from the page, exactly as the Console will make one. */
async function api(page: Page, method: string, path: string, body?: unknown): Promise<Api> {
  const xsrf = await xsrfToken(page)
  return page.evaluate(
    async ({ method, path, body, xsrf }) => {
      const headers: Record<string, string> = { Accept: 'application/json' }
      if (body !== undefined) headers['Content-Type'] = 'application/json'
      if (xsrf !== undefined) headers['X-XSRF-TOKEN'] = xsrf
      const response = await fetch(path, {
        method,
        headers,
        ...(body === undefined ? {} : { body: JSON.stringify(body) }),
      })
      const text = await response.text()
      return { status: response.status, body: text === '' ? null : (JSON.parse(text) as unknown) }
    },
    { method, path, body, xsrf },
  )
}

/** What page scripts can read: `document.cookie` excludes HttpOnly cookies. */
async function scriptVisibleCookies(page: Page): Promise<string> {
  return page.evaluate(
    () => (globalThis as unknown as { document: { cookie: string } }).document.cookie,
  )
}

async function cookie(page: Page, name: string) {
  return (await page.context().cookies()).find((c) => c.name === name)
}

test.describe('Guardian Console session authentication', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })

  test('the browser accepts the exact production session cookie on plain-HTTP localhost', async ({
    page,
  }) => {
    expect((await api(page, 'GET', '/api/v1/me')).status).toBe(401)

    const session = await cookie(page, SESSION_COOKIE)
    expect(session, 'the __Host- session cookie was rejected by Chromium').toBeDefined()
    expect(session).toMatchObject({
      name: SESSION_COOKIE,
      domain: HOST, // host-only: no leading dot, so no Domain attribute was sent
      path: '/',
      secure: true,
      httpOnly: true,
      sameSite: 'Lax',
    })

    // The token cookie is readable by script on purpose; the session cookie must not be.
    const xsrf = await cookie(page, 'XSRF-TOKEN')
    expect(xsrf).toMatchObject({ domain: HOST, httpOnly: false })
    const visibleToScript = await scriptVisibleCookies(page)
    expect(visibleToScript).toContain('XSRF-TOKEN=')
    expect(visibleToScript).not.toContain('flowlife-session')
  })

  test('signs in with the CSRF token, regenerates the session, and signs out', async ({ page }) => {
    expect((await api(page, 'GET', '/api/v1/me')).status).toBe(401)
    const anonymous = await cookie(page, SESSION_COOKIE)
    const anonymousToken = await cookie(page, 'XSRF-TOKEN')

    const login = await api(page, 'POST', '/api/v1/login', {
      email: EMAIL.toUpperCase(),
      password: PASSWORD,
    })
    expect(login.status).toBe(200)
    expect(login.body).toMatchObject({
      account: { email: EMAIL },
      person: { display_name: 'E2E Session' },
    })
    // What the account may do comes back as capability identifiers, never as role names (none, here).
    expect(login.body).toMatchObject({ capabilities: [] })
    expect(Object.keys(login.body as object)).toEqual([
      'account',
      'person',
      'capabilities',
      'session',
      'mfa',
    ])

    // The session id and CSRF token were both regenerated by signing in.
    const signedIn = await cookie(page, SESSION_COOKIE)
    expect(signedIn?.value).not.toBe(anonymous?.value)
    expect((await cookie(page, 'XSRF-TOKEN'))?.value).not.toBe(anonymousToken?.value)

    // The browser returns the cookie by itself: no script ever touched it.
    const me = await api(page, 'GET', '/api/v1/me')
    expect(me.status).toBe(200)
    expect(me.body).toMatchObject({ account: { email: EMAIL }, capabilities: [] })

    expect((await api(page, 'POST', '/api/v1/logout')).status).toBe(204)
    expect((await api(page, 'GET', '/api/v1/me')).status).toBe(401)
    expect((await cookie(page, SESSION_COOKIE))?.value).not.toBe(signedIn?.value)
  })

  test('a Console account is signed in by password AND code: the password alone establishes no session', async ({
    page,
  }) => {
    expect((await api(page, 'GET', '/api/v1/me')).status).toBe(401)

    const password = await api(page, 'POST', '/api/v1/login', {
      email: GUARDIAN,
      password: GUARDIAN_PASSWORD,
    })
    // 202, not 200: the password was right and NOTHING is established but a pending sign-in.
    expect(password.status).toBe(202)
    expect(Object.keys(password.body as object)).toEqual(['next', 'expires_at'])
    expect(password.body).toMatchObject({ next: 'challenge' })
    expect((await api(page, 'GET', '/api/v1/me')).status).toBe(401)
    const pending = await cookie(page, SESSION_COOKIE)

    const wrong = await api(page, 'POST', '/api/v1/mfa/challenge', { code: '000000' })
    expect(wrong.status).toBe(422)
    expect((await api(page, 'GET', '/api/v1/me')).status).toBe(401)

    const done = await api(page, 'POST', '/api/v1/mfa/challenge', {
      code: await nextCode(GUARDIAN_SECRET),
    })
    expect(done.status).toBe(200)
    expect(done.body).toMatchObject({
      capabilities: ['console.access'],
      mfa: { enrolled: true, recovery_codes_remaining: 10 },
    })
    // The session id was regenerated by completing the sign-in, and the browser cannot read it.
    const signedIn = await cookie(page, SESSION_COOKIE)
    expect(signedIn?.value).not.toBe(pending?.value)
    expect(signedIn).toMatchObject({ httpOnly: true, secure: true, sameSite: 'Lax' })
    expect(await scriptVisibleCookies(page)).not.toContain('flowlife-session')
    expect((await api(page, 'GET', '/api/v1/me')).status).toBe(200)
    await api(page, 'POST', '/api/v1/logout')
  })

  test('answers the same to a wrong password and an unknown address', async ({ page }) => {
    await api(page, 'GET', '/api/v1/me')

    const wrong = await api(page, 'POST', '/api/v1/login', { email: EMAIL, password: 'wrong' })
    const unknown = await api(page, 'POST', '/api/v1/login', {
      email: 'nobody@example.org',
      password: 'wrong',
    })

    expect(wrong).toEqual(unknown)
    expect(wrong.status).toBe(401)
  })

  test('a cross-site POST cannot end the signed-in session', async ({ page, context }) => {
    await api(page, 'GET', '/api/v1/me')
    expect(
      (await api(page, 'POST', '/api/v1/login', { email: EMAIL, password: PASSWORD })).status,
    ).toBe(200)

    // A different SITE: the gateway's catch-all answers here, and 127.0.0.1 is not
    // commons.flowlife.localhost. It attacks with the user's browser and their cookies.
    const attacker = await context.newPage()
    await attacker.goto(`http://127.0.0.1:${new URL(page.url()).port}/`)
    const attempt = await attacker.evaluate(
      async (target) => {
        try {
          await fetch(target, { method: 'POST', mode: 'no-cors', credentials: 'include' })
          return 'sent'
        } catch {
          // Since ADR 0026 the API answers `Cross-Origin-Resource-Policy: same-origin`, so the
          // browser now refuses this opaque cross-origin request before it is even dispatched.
          // The defence moved EARLIER; what must not change is the outcome asserted below.
          return 'refused by the browser'
        }
      },
      `http://${HOST}:${new URL(page.url()).port}/api/v1/logout`,
    )
    await attacker.close()
    expect(['sent', 'refused by the browser']).toContain(attempt)

    // Still signed in. Three independent things say so now: the browser's own cross-origin resource
    // policy, SameSite=Lax withholding the cookie, and CSRF protection refusing the request.
    expect((await api(page, 'GET', '/api/v1/me')).status).toBe(200)
    await api(page, 'POST', '/api/v1/logout')
  })

  test('grants a cross-origin page no access: there is no CORS', async ({ page, context }) => {
    const attacker = await context.newPage()
    await attacker.goto(`http://127.0.0.1:${new URL(page.url()).port}/`)

    const outcome = await attacker.evaluate(
      async (target) => {
        try {
          await fetch(target, { credentials: 'include' })
          return 'readable'
        } catch {
          return 'blocked by CORS'
        }
      },
      `http://${HOST}:${new URL(page.url()).port}/api/v1/me`,
    )

    expect(outcome).toBe('blocked by CORS')
  })

  test('refuses state-changing requests that carry no CSRF protection', async ({
    request,
    baseURL,
  }) => {
    // Node cannot resolve *.localhost, so talk to the gateway by address and present the
    // real hostname, marking the request as the browser would if it came from another site.
    const port = new URL(baseURL ?? '').port
    for (const site of ['cross-site', 'same-site']) {
      const response = await request.post(`http://127.0.0.1:${port}/api/v1/login`, {
        headers: { Host: `${HOST}:${port}`, 'Sec-Fetch-Site': site, Accept: 'application/json' },
        data: { email: EMAIL, password: PASSWORD },
      })
      expect(response.status(), site).toBe(419)
    }
  })
})
